#注释: 字典类型：   key名[空格，可有可无]:[空格][值]
#name :  "Tom"
#age: 20


#注释: 列表。 格式：-[空格][值]
#  - 10
#  - 20
#  - 30

#列表[键是info，值是列表]
- info:
    - 10
    - 20
    - 30

#如果有多个配参，之间用---隔开
---
# 开关, python会自动将on识别为True，将off识别为False
mode: on
mode1: off